name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: gitea.other.svc.cluster.local:3000/${{ github.repository_owner }}/kubernetes-repo-runner:latest
    steps:
      - name: Rollout restart
        run: |
          kubectl rollout restart deployment/mesh-gateway deployment/room-server deployment/home-auto-client deployment/observer -n meshcore
          kubectl rollout status deployment/mesh-gateway deployment/room-server deployment/home-auto-client deployment/observer -n meshcore --timeout=300s
